UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REFILL INK | Dest: BILLING | Req by: MERLINE' WHERE remarks = 'Legacy Quick Pull: REFILL INK (Dest: BILLING)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: DELAY REQUEST | Dest: HR | Req by: PALACAY' WHERE remarks = 'Legacy Quick Pull: DELAY REQUEST (Dest: HR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: SERVER | Dest: MAIN OFFICE | Req by: JENMAR' WHERE remarks = 'Legacy Quick Pull: SERVER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WRITING | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: WRITING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WRITING | Dest: HR | Req by: BETHLEHEM' WHERE remarks = 'Legacy Quick Pull: WRITING (Dest: HR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CORRECTION | Dest: OPERATION | Req by: JENMAR' WHERE remarks = 'Legacy Quick Pull: CORRECTION (Dest: OPERATION)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RESTOCK | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: RESTOCK (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR ID | Dest: MAIN OFFICE | Req by: SHARON' WHERE remarks = 'Legacy Quick Pull: FOR ID (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WAITING AREA | Dest: MAIN OFFICE | Req by: GUARD' WHERE remarks = 'Legacy Quick Pull: WAITING AREA (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR SERVER | Dest: MAIN OFFICE | Req by: JENMAR' WHERE remarks = 'Legacy Quick Pull: FOR SERVER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: ATD | Dest: PRODUCTION | Req by: MAAM SHIIN' WHERE remarks = 'Legacy Quick Pull: ATD (Dest: PRODUCTION)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RUN OUT OF PAPER | Dest: BILLING | Req by: BACULANTA' WHERE remarks = 'Legacy Quick Pull: RUN OUT OF PAPER (Dest: BILLING)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: XEROX | Dest: HR | Req by: MURPHY' WHERE remarks = 'Legacy Quick Pull: XEROX (Dest: HR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: EMPTY | Dest: MAIN OFFICE | Req by: JANET G. SUILO' WHERE remarks = 'Legacy Quick Pull: EMPTY (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: NEWLY HIRED | Dest: BILLING | Req by: NICOLE GARCIA' WHERE remarks = 'Legacy Quick Pull: NEWLY HIRED (Dest: BILLING)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REQUEST SATELITE | Dest: SATELITE OFFICE | Req by: MARVIN GOROSPE' WHERE remarks = 'Legacy Quick Pull: REQUEST SATELITE (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: NEW | Dest: MAIN OFFICE | Req by: MAAM SHIN' WHERE remarks = 'Legacy Quick Pull: NEW (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REQUEST | Dest: ZAMBOANGA CITY | Req by: RICKY NARCE' WHERE remarks = 'Legacy Quick Pull: REQUEST (Dest: ZAMBOANGA CITY)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REPLACE EMPTY | Dest: JOGIE SERVICES | Req by: BORLEY' WHERE remarks = 'Legacy Quick Pull: REPLACE EMPTY (Dest: JOGIE SERVICES)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR PACKING | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: FOR PACKING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RESTOCK | Dest: ZAMBOANGA | Req by: SIR RICKY' WHERE remarks = 'Legacy Quick Pull: RESTOCK (Dest: ZAMBOANGA)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RESTOCK MAIN OFFICE | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: RESTOCK MAIN OFFICE (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: PRINTING | Dest: MAIN OFFICE | Req by: SIR MARK' WHERE remarks = 'Legacy Quick Pull: PRINTING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: PRINTING PAYSLIP | Dest: MAIN OFFICE | Req by: SIR GELO' WHERE remarks = 'Legacy Quick Pull: PRINTING PAYSLIP (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR NEW OFFICE FRONT DOOR AND BACKDOOR | Dest: MAIN OFFICE | Req by: JANET G. SUILO' WHERE remarks = 'Legacy Quick Pull: FOR NEW OFFICE FRONT DOOR AND BACKDOOR (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: 2 NEW BALLPEN WITH TAPE REPLACEMENT | Dest: MAIN OFFICE | Req by: GENMAR' WHERE remarks = 'Legacy Quick Pull: 2 NEW BALLPEN WITH TAPE REPLACEMENT (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: NEW CALCULATOR 1 | Dest: BILLING MAIN OFFICE | Req by: MERLIN' WHERE remarks = 'Legacy Quick Pull: NEW CALCULATOR 1 (Dest: BILLING MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR TRASH | Dest: BILLING MAIN OFFICE | Req by: MERLIN' WHERE remarks = 'Legacy Quick Pull: FOR TRASH (Dest: BILLING MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: GAISANO BRANCH | Dest: GAISANO GENSAN | Req by: AILYN BARRIENTOS' WHERE remarks = 'Legacy Quick Pull: GAISANO BRANCH (Dest: GAISANO GENSAN)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REFILL | Dest: FINANCE MAIN OFFICE | Req by: MARY JANE TALADTAD' WHERE remarks = 'Legacy Quick Pull: REFILL (Dest: FINANCE MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WITH EMPTY | Dest: MAIN OFFICE | Req by: MAAM KWEEN' WHERE remarks = 'Legacy Quick Pull: WITH EMPTY (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WITHOUT BOT | Dest: MAIN OFFICE | Req by: KARL' WHERE remarks = 'Legacy Quick Pull: WITHOUT BOT (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: SIR MARK | Dest: MAIN OFFICE | Req by: EDSZAR LAPAS' WHERE remarks = 'Legacy Quick Pull: SIR MARK (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: TRANSMITTAL | Dest: BILLING MAIN OFFICE | Req by: MERLIN BEWAN' WHERE remarks = 'Legacy Quick Pull: TRANSMITTAL (Dest: BILLING MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR DOCUMENTS | Dest: MAIN OFFICE | Req by: MARIE' WHERE remarks = 'Legacy Quick Pull: FOR DOCUMENTS (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REPLACE | Dest: JOGIE SERVICES | Req by: TPJ OPERATOR' WHERE remarks = 'Legacy Quick Pull: REPLACE (Dest: JOGIE SERVICES)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: PAYROLL | Dest: MAIN OFFICE | Req by: SIR GELO' WHERE remarks = 'Legacy Quick Pull: PAYROLL (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BPI | Dest: HR MAIN OFFICE | Req by: SIR GENMAR' WHERE remarks = 'Legacy Quick Pull: BPI (Dest: HR MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: SATELITE OFFICE REQUEST | Dest: SATELITE OFFICE | Req by: RANDELS FRANCIS' WHERE remarks = 'Legacy Quick Pull: SATELITE OFFICE REQUEST (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: SATELITE OFFICE RESTOCK | Dest: SATELITE OFFICE | Req by: RANDELS FRANCIS' WHERE remarks = 'Legacy Quick Pull: SATELITE OFFICE RESTOCK (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR DOCUMENTS | Dest: SATELITE OFFICE | Req by: RANDELS FRANCIS' WHERE remarks = 'Legacy Quick Pull: FOR DOCUMENTS (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BILLING SATELITE OFFICE | Dest: SATELITE OFFICE | Req by: MAYETH' WHERE remarks = 'Legacy Quick Pull: BILLING SATELITE OFFICE (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: ACCOUNTING | Dest: MAIN OFFICE | Req by: MAAM CHE' WHERE remarks = 'Legacy Quick Pull: ACCOUNTING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FINANCE | Dest: MAIN OFFICE | Req by: MARIE' WHERE remarks = 'Legacy Quick Pull: FINANCE (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BILLING | Dest: MAIN OFFICE | Req by: MAAM R' WHERE remarks = 'Legacy Quick Pull: BILLING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: DOCUMENTS | Dest: MAIN OFFICE | Req by: MAAM SHIN' WHERE remarks = 'Legacy Quick Pull: DOCUMENTS (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REPLACEMENT AND NEW HIGHLIGHTER | Dest: MAIN OFFICE | Req by: MAAM CHE' WHERE remarks = 'Legacy Quick Pull: REPLACEMENT AND NEW HIGHLIGHTER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BIILING | Dest: MAIN OFFICE | Req by: MARK' WHERE remarks = 'Legacy Quick Pull: BIILING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REPLACEMENT | Dest: MAIN OFFICE | Req by: KAIJI' WHERE remarks = 'Legacy Quick Pull: REPLACEMENT (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CLEANLINESS | Dest: MAIN OFFICE | Req by: MAAM JESSA' WHERE remarks = 'Legacy Quick Pull: CLEANLINESS (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: ADDITIONAL | Dest: HR MAIN OFFICE | Req by: MURPHY M. ACADEMIA' WHERE remarks = 'Legacy Quick Pull: ADDITIONAL (Dest: HR MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: HR | Dest: MAIN OFFICE | Req by: SIR MURPHY' WHERE remarks = 'Legacy Quick Pull: HR (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REPLACEMENT | Dest: SATELITE OFFICE | Req by: MECHELLE' WHERE remarks = 'Legacy Quick Pull: REPLACEMENT (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR QR CODE | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: FOR QR CODE (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CUTTING QR CODE STICKER | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: CUTTING QR CODE STICKER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REQUEST | Dest: MAIN OFFICE | Req by: MAAM KWEEN' WHERE remarks = 'Legacy Quick Pull: REQUEST (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BPI FORM | Dest: MAIN OFFICE | Req by: SIR JEMAR' WHERE remarks = 'Legacy Quick Pull: BPI FORM (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WITH EMPTY | Dest: SATELITE OFFICE | Req by: JACKIELYN G. LUMBOS' WHERE remarks = 'Legacy Quick Pull: WITH EMPTY (Dest: SATELITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CLEANLINESS | Dest: MAIN OFFICE CR | Req by: MARIANE' WHERE remarks = 'Legacy Quick Pull: CLEANLINESS (Dest: MAIN OFFICE CR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OFFICE | Dest: MAIN OFFICE | Req by: MAAM APRIL' WHERE remarks = 'Legacy Quick Pull: OFFICE (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BPI FORMS | Dest: MAIN OFFICE | Req by: SIR JEMAR' WHERE remarks = 'Legacy Quick Pull: BPI FORMS (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR GUARD | Dest: MAIN OFFICE | Req by: MAAM BHEA' WHERE remarks = 'Legacy Quick Pull: FOR GUARD (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR THE MONTH OF APRIL 2026 | Dest: SATELITE OFFICE/SUPERVISOR | Req by: ARAZ' WHERE remarks = 'Legacy Quick Pull: FOR THE MONTH OF APRIL 2026 (Dest: SATELITE OFFICE/SUPERVISOR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BILLING SATELLITE | Dest: SATELLITE OFFICE | Req by: SIR MARVIN' WHERE remarks = 'Legacy Quick Pull: BILLING SATELLITE (Dest: SATELLITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: FOR APPLICANTS | Dest: OUTSIDE MAIN OFFICE | Req by: GUARD' WHERE remarks = 'Legacy Quick Pull: FOR APPLICANTS (Dest: OUTSIDE MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: DOCUMENTS | Dest: MAIN  OFFICE | Req by: BETLEHEM' WHERE remarks = 'Legacy Quick Pull: DOCUMENTS (Dest: MAIN  OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: INVENTORY | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: INVENTORY (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RECORDING | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: RECORDING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: RECORDING | Dest: SATELLITE OFFICE | Req by: MAAM ANEBA' WHERE remarks = 'Legacy Quick Pull: RECORDING (Dest: SATELLITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CLEANING | Dest: MAIN OFFICE | Req by: ILLA KIM MAYO' WHERE remarks = 'Legacy Quick Pull: CLEANING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: SECOND FLOOR NEW BUILDING | Dest: MAIN OFFICE | Req by: JANET G SUILO' WHERE remarks = 'Legacy Quick Pull: SECOND FLOOR NEW BUILDING (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OPERATION | Dest: MAIN OFICE | Req by: JEMAR BARRERA' WHERE remarks = 'Legacy Quick Pull: OPERATION (Dest: MAIN OFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OPERATION | Dest: MAIN OFFICE | Req by: JEMAR BARRERA' WHERE remarks = 'Legacy Quick Pull: OPERATION (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: COLLECTION | Dest: MAIN OFFICE | Req by: SIR KARL' WHERE remarks = 'Legacy Quick Pull: COLLECTION (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: NEW | Dest: VAAS MAKAR | Req by: GOMEZ CHALESKA ANN' WHERE remarks = 'Legacy Quick Pull: NEW (Dest: VAAS MAKAR)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: REQUEST | Dest: SATELLITE OFFICE | Req by: DOJILLO MARISA' WHERE remarks = 'Legacy Quick Pull: REQUEST (Dest: SATELLITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: HR | Dest: SATELLITE OFFICE | Req by: BETHLEHEM' WHERE remarks = 'Legacy Quick Pull: HR (Dest: SATELLITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OPERATION | Dest: OUTSIDE | Req by: BORLING' WHERE remarks = 'Legacy Quick Pull: OPERATION (Dest: OUTSIDE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: BAKERY | Dest: OUTSIDE | Req by: MARTIN GANUAY' WHERE remarks = 'Legacy Quick Pull: BAKERY (Dest: OUTSIDE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: PRINTER COVER | Dest: MAIN OFFICE | Req by: SIR KIM' WHERE remarks = 'Legacy Quick Pull: PRINTER COVER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OFFICE WORK | Dest: OUTSIDE OFFICE | Req by: SAFI CENTRO' WHERE remarks = 'Legacy Quick Pull: OFFICE WORK (Dest: OUTSIDE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: MESSENGER | Dest: MAIN OFFICE | Req by: SIR KIM' WHERE remarks = 'Legacy Quick Pull: MESSENGER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: ID LAMINATION | Dest: MAIN OFFICE | Req by: CHRISTINE' WHERE remarks = 'Legacy Quick Pull: ID LAMINATION (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: STICKER | Dest: MAIN OFFICE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: STICKER (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: WAREHOUSE | Dest: WAREHOUSE | Req by: EDRON' WHERE remarks = 'Legacy Quick Pull: WAREHOUSE (Dest: WAREHOUSE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: ARCOBA TAILORING | Dest: OUTSIDE TAILORING | Req by: EDRON D. MAGUALE' WHERE remarks = 'Legacy Quick Pull: ARCOBA TAILORING (Dest: OUTSIDE TAILORING)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: JBV FILES | Dest: MAIN OFFICE | Req by: JANET G. SUILO' WHERE remarks = 'Legacy Quick Pull: JBV FILES (Dest: MAIN OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: GAISANO | Dest: GAISANO | Req by: MAAM BETH' WHERE remarks = 'Legacy Quick Pull: GAISANO (Dest: GAISANO)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: OPERATION | Dest: SATELLITE OFFICE | Req by: ELMER AGONOS' WHERE remarks = 'Legacy Quick Pull: OPERATION (Dest: SATELLITE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: MESSENGER | Dest: OUTSIDE OFFICE | Req by: SIR KIM' WHERE remarks = 'Legacy Quick Pull: MESSENGER (Dest: OUTSIDE OFFICE)';
UPDATE "ProductTransaction" SET remarks = 'Legacy Quick Pull: CENTRO EXPRESS | Dest: BAKERY | Req by: MAAM MARIANE' WHERE remarks = 'Legacy Quick Pull: CENTRO EXPRESS (Dest: BAKERY)';
